### ISSUE TITLE
Facing problem in SHD estimation

### ISSUE THREAD

**Issue by UzmaHasan** [cmu-phil/causal-learn#86]
Hi. I am getting the following **KeyError** whenever I try to estimate the **SHD** using the true graph and estimated graph. 

`Traceback (most recent call last):
  File "test_GES_metrics.py", line 25, in <module>
    shd = SHD(truth_cpdag, est)
  File "F:\REPOSITORIES\causal-learn\causallearn\graph\SHD.py", line 33, in __init__
    if (not truth.get_edge(truth.get_node(nodes_name[i]), truth.get_node(nodes_name[j]))) and est.get_edge(
  File "F:\REPOSITORIES\causal-learn\causallearn\graph\GeneralGraph.py", line 530, in get_edge
    i = self.node_map[node1]
KeyError: None`

I am unable to figure out why this mapping error is happening and how to solve this.

**Comment by UzmaHasan** [comment]
Hi again. I just solved the issue. I was using the original variable names initially in the txt file for the ground truth graph. But, later when I renamed the variables as X1;X2;....... and so on, then the above mentioned error got resolved and the code works fine now! 

Appreciate the way this repository is organized and well-documented!

**Comment by UzmaHasan** [comment]
Hi again. I just solved the issue. I was using the original variable names initially in the txt file for the ground truth graph. But, later when I renamed the variables as X1;X2;....... and so on, then the above mentioned error got resolved and the code works fine now!

Appreciate the way this repository is organized and well-documented!
